package jhelp.antology;

/**
 * Created by jhelp on 25/07/17.
 */
public enum RuleConstraint
{
    SUBJECTS_EQUALS,
    PREDICATES_EQUALS,
    INFORMATION_EQUALS,
    FIRST_SUBJECT_EQUALS_SECOND_PREDICATE,
    FIRST_SUBJECT_EQUALS_SECOND_INFORMATION,
    FIRST_PREDICATE_EQUALS_SECOND_SUBJECT,
    FIRST_PREDICATE_EQUALS_SECOND_INFORMATION,
    FIRST_INFORMATION_EQUALS_SECOND_SUBJECT,
    FIRST_INFORMATION_EQUALS_SECOND_PREDICATE
}
